---
- hosts: mysql
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:
    - name: "Instalando pacotes do sistema nescessarios para o mysql"
      apt:
        name: ["mysql-server-5.6", "python-mysqldb"]
        state: latest
      become: yes

    - name: "Criando schema no MySQL"
      mysql_db:
        name: "{{ DATABASE_NAME }}"
        login_user: root
        state: present

    - name: "Criando usuario no MySQL"
      mysql_user:
        login_user: root
        name: "{{ DATABASE_USER }}"
        password: "{{ DATABASE_PASSWORD }}"
        priv: "{{ DATABASE_NAME }}.*:ALL"
        state: present
        host: "{{ item }}"
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - '{{ HOST_WORDPRESS }}'

    - name: "Copiando arquivo de configuração do mysql"
      copy:
        src: "../files/my.cnf"
        dest: "/etc/mysql/my.cnf"
      become: yes
      notify:
        - restart mysql

- hosts: wordpress
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: "Instalando pacotes do sistema nescessarios para o wordpress"
      apt:
        name:
          [
            "php5",
            "apache2",
            "libapache2-mod-php5",
            "php5-gd",
            "libssh2-php",
            "php5-mcrypt",
            "php5-mysql",
          ]
        state: latest
      become: yes

    - name: "Fazendo download da versão 5.0 do wordpress"
      get_url:
        url: https://wordpress.org/wordpress-5.0.tar.gz
        dest: "/tmp/wordpress.tar.gz"

    - name: "Descompactando arquivo do wordpress"
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www/"
        remote_src: yes
      become: yes

    - name: "Fazendo uma cópia do arquivo de exemplo de configuração do wordpress"
      copy:
        src: "{{ WORDPRESS_DIR }}/wp-config-sample.php"
        dest: "{{ WORDPRESS_DIR }}/wp-config.php"
        remote_src: yes
      become: yes

    - name: "Substituindo variaveis de ambiente no arquivo de configuração do wordpress"
      replace:
        path: "{{ WORDPRESS_DIR }}/wp-config.php"
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: "database_name_here", value: "{{ DATABASE_NAME }}" }
        - { regex: "username_here", value: "{{ DATABASE_USER }}" }
        - { regex: "password_here", value: "{{ DATABASE_PASSWORD }}" }
        - { regex: "localhost", value: "{{ HOST_MYSQL }}" }
      become: yes

    - name: "Copiando arquivo de configuração do apache"
      template:
        src: "../templates/000-default.conf.j2"
        dest: "/etc/apache2/sites-available/000-default.conf"
      become: yes
      notify:
        - restart apache
